### ISSUE TITLE
Weird behavior when carts travel through unloaded blocks

### ISSUE THREAD

**Issue by jfanjoy** [joe7575/minecart#12]
Is there a maximum distance which minecarts can travel between loaded buffers?

I have taken extra care to ensure that all rail buffers are force loaded and routes are stored in each direction, but I still do not seem to be able to rely on carts arriving at their destinations. When I walk the tracks I find dozens of carts essentially stuck along the route at several points, many of which appear to be generated by the buffer (I only place one numbered cart on each track). Sometimes I will see the number of a cart that just passed me coming up as I continue the route, and there are a few spots where phantom carts appear and disappear on occasion. Initially I suspected the issue was due to force load limits being reached on the server, but I've made adjustments and the behavior persists.

All buffers are force loaded using the TA force load block, and I've confirmed that the defined forceload limits have not been reached. When I find carts they are usually just outside of these force loaded areas (1 or 2 mapblocks away). I have destroyed and re-created my buffers and even parts of the track in hopes to make use of minecarts to transport materials up to where I have my machines to process it, but so far it seems like at least for the longer routes (>= 100m) I am unable to trust that material will arrive at the destination.

**Comment by joe7575** [comment]
I can't explain it at the moment. There are routes on my server that are thousands of blocks long and I'm not aware of any problems. 

There is no length limit. Are you having lag issues on your server? It may help to reduce the [max speed](https://github.com/joe7575/minecart/blob/master/rails.lua#L20)

**Comment by joe7575** [comment]
Check your file "debug.txt". You should find messages from the minecart mod:

```
2023-09-24 12:56:57: WARNING[Server]: [Minecart] Cart Minsc/3 stopped at (-115,17,-1357)!
2023-10-01 11:58:04: WARNING[Server]: [Minecart] Cart Minsc/3 stopped at (-115,18,-1349)!
2023-10-01 16:34:16: WARNING[Server]: [Minecart] Cart mony/1 without pos!
2023-10-01 16:34:24: WARNING[Server]: [Minecart] Cart mony/1 without pos!
```

**Comment by jfanjoy** [comment]
I don't have a debug.txt but my minetest.log does not include any warnings from the minecart mod. I also don't experience much lag while playing, but the server is pretty small and does seem to have some swap space used and not much free memory. I usually have a system load well below 1. Generally it's just me and one other person playing but we are looking at perhaps a beefier server. So far the logs and player experience don't indicate any issues even if resource availability seems a bit tight.

I will try slowing the carts down. So far I haven't set out any speed limits, but if you think this might improve the behavior then it's worth a try.
